# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'clouddse_jfrog'
    sourceRepo: 'anusha-test-npm'